name: cmake-build

on:
  push:
    branches: [ "main" ]
    paths:
      - include/**
      - src/**
      - .github/workflows/cmake-build.yml
      - CMakeLists.txt
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-latest
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os:
    #       - ubuntu-latest
    #       - windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Debug -S . -B build

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --parallel
